### ISSUE TITLE
TypeError: pimcore.bundle.outputDataConfigToolkit is undefined

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/web2print-tools#17]
Pimcore `6.8.10`
Web2Print `dev-master`

When clicking the grid icon nothing happens and this error appears in the browser console:

![image](https://user-images.githubusercontent.com/279826/110634588-6989e400-81aa-11eb-8035-ce530ac3b7ee.png)

**Comment by fashxp** [comment]
cannot reproduced with pimcore 6.9 and latest release.

**Comment by NiklasBr** [comment]
Still happens with 4.0.0 and 6.9.1:

![image](https://user-images.githubusercontent.com/279826/114532617-4b058580-9c4d-11eb-863f-565edc0d1227.png)

**Comment by NiklasBr** [comment]
Still happens with 4.0.0 in 6.9.1:

![image](https://user-images.githubusercontent.com/279826/114532684-5a84ce80-9c4d-11eb-84fe-529288ca136d.png)

**Comment by fashxp** [comment]
can you please provide more detailled steps to reproduce, thx.

**Comment by NiklasBr** [comment]
Tried to reproduce with version 4.0.1 but can no longer install it. Can you have a look at the other issue first because it is not usable at all right now.
