### ISSUE TITLE
Migration error, pimcore.settings_store doesn't exist

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/web2print-tools#20]
When trying to install the latest version of this bundle with Composer and using Pimcore 6.9.1 I get the following error when running this command:

```sh
bin/console pimcore:bundle:install --no-cache-clear Web2PrintToolsBundle
```

```
[ERROR] An exception occurred while executing 'SELECT * FROM settings_store WHERE id = ? AND scope = ?' with params
["BUNDLE_INSTALLED__Web2PrintToolsBundle\\Web2PrintToolsBundle", "pimcore"]:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore.settings_store' doesn't exist
```

**Comment by fashxp** [comment]
please make sure that your pimcore migrations are executed properly. this table should be created by pimcore.

**Comment by NiklasBr** [comment]
Yes, migrations were done manually [because they are not done automatically](https://github.com/pimcore/skeleton/pull/22).

**Comment by fashxp** [comment]
It is not about bundle migrations, it is about core migrations ... see https://github.com/pimcore/pimcore/pull/8332

This is not a problem of this bundle

**Comment by NiklasBr** [comment]
Ok, thanks, added an issue in pimcore/pimcore instead,
