### ISSUE TITLE
[Improvement]: Trigger a comprehensive error if open datadefinition is clicked without any class

### ISSUE THREAD

**Issue by Yivan** [pimcore/web2print-tools#24]
### Improvement description

Clicking on the picto open datadefinition without having filled prior the class send an exception.

![image](https://user-images.githubusercontent.com/9025839/134368554-7aebbeae-609c-406a-8da0-5692baa2068c.png)

A clean message saying somethings like "Please fill the class", will be better / seems to the end user not buggy.

By the way, the hover on this picto is not translated it seems:

![image](https://user-images.githubusercontent.com/9025839/134368718-1180ee6c-092b-4b22-856f-136cfb54feca.png)

Thanks!

**Comment by dvesh3** [comment]
Fixed by #25
