### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by fashxp** [pimcore/web2print-tools#51]
### Expected behavior

.

### Actual behavior

.

### Steps to reproduce

.

**Comment by kingjia90** [comment]
Related to this change https://github.com/pimcore/output-data-config-toolkit/pull/70
https://github.com/pimcore/web2print-tools/blob/6b86cc060dc9f9d25b31a9b58890e660b8c7feb9/src/FavoriteOutputDefinition.php#L93-L96

**Comment by Corepex** [comment]
It looks like the `o_` changes haven't been implemented yet - should I do that for the whole bundle or is there a reason why this hasn't been done yet?

**Comment by Corepex** [comment]
As discussed in the daily I will implement the `o_` bc layer for the whole bundle
