### ISSUE TITLE
[Improvement]: migration_versions in demo dump

### ISSUE THREAD

**Issue by saitho** [pimcore/web2print-tools#78]
### Improvement description

I set up the demo system with Pimcore 11 and noticed that running the migration if the Web2PrintToolsBundle fails, as it can not rename the column as it was already updated:

> An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o_classId' in 'bundle_web2print_favorite_outputdefinitions'

I think the data for `migration_versions` table should also be provided in the demo dump. This would then contain the information, which migrations have already run.

**Comment by kingjia90** [comment]
Thank you for the report!

It's likely fixed by https://github.com/pimcore/web2print-tools/pull/77, just needs to be released

**Comment by dvesh3** [comment]
Fixed by #77

**Comment by saitho** [comment]
Migration Version20230124103907 also changes the requirement for MariaDB.

According to [latest documentation](https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/System_Requirements/#database-server) of Pimcore MariaDB >=10.3 is required.
`RENAME COLUMN` is only available from MariaDB 10.5.2, see [documentation](https://mariadb.com/kb/en/alter-table/#rename-column).

This should be documented somewhere. :)

**Comment by dvesh3** [comment]
or should we use `CHANGE COLUMN` ? @kingjia90 wdyt?

**Comment by kingjia90** [comment]
Yes, we need to replace to CHANGE COLUMN, it's affecting also in other 4 other bundles
https://github.com/search?q=org%3Apimcore+%22RENAME+COLUMN%22&type=code

Can't bump minimum requirement to MariaDB 10.5.2 (at least not yet)
